version: '3.8'

volumes:
  mysql_data:

services:
  mysql:
    image: mysql:8.0
    container_name: bank_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: my_db
      MYSQL_USER: bestuser
      MYSQL_PASSWORD: bestuser
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpass"]
      timeout: 20s
      retries: 10
      start_period: 40s
  
  app:
    image: zzzrbn/bank_rest-main:latest
    container_name: bank_rest-main
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/my_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: bestuser
      SPRING_DATASOURCE_PASSWORD: bestuser
      JWT_SECRET: bankRestMainMySecretKeyForJWTIsForMyTestApplication
      ENCRYPTION_KEY: shifrovanieDlyaNomerovCart
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge